### ISSUE TITLE
Deleting groups fails due to foreign key constraint

### ISSUE THREAD

**Issue by zimsneexh** [VelocityVMM/Velocity#10]
Deleting groups (even without subgroups) fails due to violating a FOREIGN KEY constraint. This is reproducible in the webinterface (and I assume in vCMD aswell?)

Response:
"FOREIGN KEY constraint failed (code: 19)"

**Comment by maxkofler** [comment]
Is there some media attached to it? I think that is currently not handled yet...

**Comment by zimsneexh** [comment]
I think it's due to memberships. Are they supposed to be removed automatically once a group is deleted?

**Comment by maxkofler** [comment]
That could be the cause, too. I think i'm missing some `ON DELETE` clauses. I even think there are none in place right now

**Comment by maxkofler** [comment]
So I reproduced the Bug and it is indeed the memberships. I think an easy `ON DELETE CASCADE` should do the job, but I will keep this issue open until I implemented something for handling Media, too.

**Comment by maxkofler** [comment]
@zimsneexh I think the issue should now be fixed on the `issue/10` branch.

**Comment by zimsneexh** [comment]
@maxkofler Seems to work, although the root group can be deleted. I don't think that's intended?

**Comment by maxkofler** [comment]
Certainly not as that would break core functionality. I will look into that, too. Thank you

**Comment by maxkofler** [comment]
I fixed the issue. Additionally I added protection for the root user

**Comment by zimsneexh** [comment]
Just tested - Works fine now
